[{
    "id": 1,
    "app_name": "Subin"
  }, {
    "id": 2,
    "app_name": "It"
  }, {
    "id": 3,
    "app_name": "Wrapsafe"
  }, {
    "id": 4,
    "app_name": "Voltsillam"
  }, {
    "id": 5,
    "app_name": "Job"
  }, {
    "id": 6,
    "app_name": "Subin"
  }, {
    "id": 7,
    "app_name": "Zathin"
  }, {
    "id": 8,
    "app_name": "Latlux"
  }, {
    "id": 9,
    "app_name": "Regrant"
  }, {
    "id": 10,
    "app_name": "Alphazap"
  }]